# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "WB3Tech"
email: "TalkToAHuman@wb3tech.com"
description: "Transform your company into a modern-day technology company."
baseurl: ""
url: "https://wb3tech.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-101949141-1"
googleAnalyticsSiteUrl: "wb3tech.com"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Head
metaKeywords: "wb3, technology, cloud, cloud native, development, operations, devops, platform, api"
twitterAccount: "@WB3Tech"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
- {permalink: "/", text: "Home"}
# - {permalink: "/fractional-cio-cto", text: "Fractional CIO & CTO"}
# - {permalink: "/continuous-delivery", text: "Continuous Delivery"}
# - {permalink: "/platform-strategy", text: "Platform Strategy"}
# - {permalink: "/software-refactoring", text: "Software Refactoring"}
# - {permalink: "/citizen-innovation", text: "Citizen Innovation"}

# Hero Block
heroImage: "WB3Tech-SectionBackground-1080x1920.png"
heroTitle: "Make Technology "
typeoutTextValues: '"", "Your Competitive Advantage", "Generate Revenue", "A Strength", "Grow Your Top Line", "#MyJam", "#MyThing"'
typeoutFallback: "Grow Your Top Line"

# About Block
aboutTitle: "What We Do For You"
aboutBlock:
 - {title: "Fractional<br>CIO & CTO", image: "fractional-cio-cto-500x417.jpg", text: "Top tier technology leadership without a full-time commitment.", link: "/fractional-cio-cto" }
 - {title: "Continuous<br>Delivery", image: "continuous-delivery-500x417.jpg", text: "Source code to customer in less than 10 minutes.", link: "/continuous-delivery" }
 - {title: "Platform<br>Stratgey", image: "platform-strategy-2-500x499.jpg", text: "Extend your business model by allowing others to leverage your core competencies for their customers.", link: "/platform-strategy" }
 - {title: "Software<br>Refactoring", image: "software-refactoring-500x333.jpg", text: "Enhance non-functional aspects of your software without changing how it works.", link: "/software-refactoring" }
 - {title: "Citizen<br>Innovation", image: "citizen-innovation-500x355.jpg", text: "Give all employees the tools & opportunity to grow your top line with technology.", link: "/citizen-innovation" }

# Latest News Block
latestNewsTitle: "Latest news"

#Contact Us
contactUsTitle: "Let's Talk About Your Problem"
contatcUsEmail: "TalkToAHuman@wb3tech.com"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/wb3tech", icon: "linkedin"}
 - {link: "https://twitter.com/intent/user?screen_name=WB3Tech", icon: "twitter"}
 - {link: "https://github.com/wb3tech", icon: "github"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:TalkToAHuman@wb3tech.com", text: "TalkToAHuman@wb3tech.com"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."